language: node_js
node_js:
 - "node"
env:
- MY_VAR=EverythignIsAwesome
- NODE_ENV=TEST
deploy:
  provider: firebase
  token:
    secure: "1/EMeAnqVIiD00_lgIgl7bWwdS6UqmpLmQJE9ZfzAHuEYRCI6ag3lp8xXGnI0m_sIe"